"""CreateSecureLinkTool per BRD FR-013.

Lightweight demo version for generating secure access links for error reports.
Contains explicit production comments marking where full implementation would occur.
"""

import secrets
from pathlib import Path
from typing import Any, Dict

from ..tools import ToolResult


class CreateSecureLinkTool:
    """Creates secure access link for validation report per BRD FR-013.
    
    Demo behavior:
    - Generates cryptographically secure access code
    - Writes access code to evidence_dir/secure_link_code.txt
    - Returns a URL pointing at the partner-accessible report location
      (SharePoint URL if provided, otherwise a local file:// URL)
    
    PRODUCTION NOTES:
    - Replace local file URLs with SharePoint secure links created via SharePointClient
    - Store access codes and link metadata in PostgreSQL secure_links table
    - Enforce expiration and access logging per BRD FR-013
    - Send access codes via secure email service (no PII in email body)
    """
    
    name = "CreateSecureLinkTool"
    
    def __call__(
        self,
        error_report_path: Path,
        evidence_dir: Path,
        run_id: str,
        sharepoint_url: str | None = None,
    ) -> ToolResult:
        """Generate secure access link for error report.
        
        Args:
            error_report_path: Path to local error report file (used for fallback URL)
            evidence_dir: Evidence bundle directory where access code should be stored
            run_id: Run identifier for tracking
            sharepoint_url: Optional URL to partner-accessible SharePoint/Dataverse
                            report location. When provided, this URL is used as the
                            base of the secure link in demo mode.
        
        Returns:
            ToolResult with secure_link_url and access_code in data
        """
        # Generate cryptographically secure access code per BRD FR-013 acceptance criteria
        # Using secrets.token_urlsafe(16) for URL-safe random token
        access_code = secrets.token_urlsafe(16)
        
        # PRODUCTION: Store access code in PostgreSQL secure_links table
        # PRODUCTION: Include expiration (7 days default), access count tracking, last accessed timestamp
        # PRODUCTION: Link access_code to error_report_path and run_id
        
        # For demo: Write access code to evidence_dir/secure_link_code.txt
        secure_link_code_file = evidence_dir / "secure_link_code.txt"
        secure_link_code_file.parent.mkdir(parents=True, exist_ok=True)
        with open(secure_link_code_file, 'w') as f:
            f.write(access_code)
        
        # PRODUCTION: Generate SharePoint secure link with Azure AD authentication
        # PRODUCTION: Use SharePoint API to create secure link with access code
        # PRODUCTION: Set link expiration and access permissions and return that URL
        
        # DEMO BEHAVIOR:
        # - If a SharePoint/simulated URL is provided (from UploadSharePointTool),
        #   use that as the base location of the secure link.
        # - Otherwise, fall back to a local file:// URL for the error_report_path.
        if sharepoint_url:
            # In demo, we return the SharePoint (or simulated) URL directly.
            # In production, this would be a code-protected URL generated by
            # SecureLinkGenerator using sharepoint_url + access_code metadata.
            secure_link_url = sharepoint_url
        else:
            # Fallback: local file URL
            secure_link_url = f"file:///{error_report_path.as_posix()}"
        
        # PRODUCTION: Send access code via secure email service (not in email body)
        # PRODUCTION: Use email service API to send access code separately from email content
        # PRODUCTION: Track email delivery status and link accesses
        
        return ToolResult(
            ok=True,
            summary=f"Generated secure link with access code for run {run_id}",
            data={
                "secure_link_url": secure_link_url,
                "access_code": access_code,
                "secure_link_code_file": str(secure_link_code_file)
            },
            warnings=[],
            blockers=[]
        )

